MyBlog.Presentation/Areas/Author/Controllers/ArticleController.cs
using MyBlog.Applicationn.DTOs.ArticleDTOs;
using MyBlog.Applicationn.Services.ArticleServices;
using MyBlog.Applicationn.Services.AuthorServices;
using MyBlog.Applicationn.Services.SubjectServices;
using MyBlog.Presentation.Areas.Author.Models.ArticleVMs;
using MyBlog.Presentation.Extentions;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace MyBlog.Presentation.Areas.Author.Controllers
{
    public class ArticleController : AuthorBaseController
    {
        private readonly IAuthorService _authorService;
        private readonly IArticleService _articleService;
        private readonly ISubjectService _subjectService;

        public ArticleController(IAuthorService authorService, IArticleService articleService, ISubjectService subjectService)
        {
            _authorService = authorService;
            _articleService = articleService;
            _subjectService = subjectService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var authorId = await _authorService.GetAuthorIdByIdentityId(userId);
            var result = await _articleService.GetAllAsync(authorId);
            var articleListVms = result.Data.Adapt<List<ArticleListVM>>();
            if (!result.IsSuccess)
            {
                NotifiyError(result.Messages);
                return View(articleListVms);
            }
            NotifiySuccess(result.Messages);
            return View(articleListVms);
        }


        public async Task<IActionResult> Create()
        {
            var createVM = new ArticleCreateVM()
            {
                Subjects = await GetSubjects()
            };
            return View(createVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ArticleCreateVM model)
        {
            if (!ModelState.IsValid)
            {
                model.Subjects = await GetSubjects();
                return View(model);
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var authorId = await _authorService.GetAuthorIdByIdentityId(userId);
            var articleCreateDto = model.Adapt<ArticleCreateDTO>();
            articleCreateDto.ReadTime = await model.Content.CalculeTimeForString();
            articleCreateDto.AuthorId = authorId;
            if (model.NewImage !=null && model.NewImage.Length>0)
            {
                articleCreateDto.Image = await model.NewImage.StringToByteArrayAsync();
            }
            var result = await _articleService.AddAsync(articleCreateDto);
            if (!result.IsSuccess)
            {
                NotifiyError(result.Messages);
                model.Subjects = await GetSubjects();
                return View(model);
            }
            NotifiySuccess(result.Messages);
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Delete(Guid id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var authorId = await _authorService.GetAuthorIdByIdentityId(userId);
            var result = await _articleService.DeleteAsync(id,authorId);
            if (!result.IsSuccess)
            {
                NotifiyError(result.Messages);
                return RedirectToAction("Index");
            }
            NotifiySuccess(result.Messages);
            return RedirectToAction("Index");
        }

        private async Task<SelectList> GetSubjects(Guid? subjectId = null)
        {
            var subjects = (await _subjectService.GetAllAsync()).Data;
            return new SelectList(subjects.Select(src => new SelectListItem
            {
                Value = src.Id.ToString(),
                Text = src.Name,
                Selected = src.Id == (subjectId != null ? subjectId.Value : subjectId)
            }).OrderBy(x => x.Text), "Value", "Text");
        }
    }
}

MyBlog.Presentation/Areas/Author/Controllers/SubjectController.cs
using MyBlog.Applicationn.DTOs.SubjectDTOs;
using MyBlog.Applicationn.Services.AuthorServices;
using MyBlog.Applicationn.Services.SubjectServices;
using MyBlog.Presentation.Areas.Author.Models.SubjectVMs;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MyBlog.Presentation.Areas.Author.Controllers
{
    public class SubjectController : AuthorBaseController
    {
        private readonly ISubjectService _subjectService;
        private readonly IAuthorService _authorService;

        public SubjectController(ISubjectService subjectService, IAuthorService authorService)
        {
            _subjectService = subjectService;
            _authorService = authorService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _subjectService.GetAllAsync();
            if (!result.IsSuccess)
            {
                NotifiyError(result.Messages);
                return View(result.Data.Adapt<List<SubjectListVM>>());
            }
            NotifiySuccess(result.Messages);
            return View(result.Data.Adapt<List<SubjectListVM>>());
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(SubjectCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var result = await _subjectService.AddAsync(model.Adapt<SubjectCreateDTO>());
                if (!result.IsSuccess)
                {
                    NotifiyError(result.Messages);
                    return View(model);
                }
                NotifiySuccess(result.Messages);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _subjectService.DeleteAsync(id);
            if (!result.IsSuccess)
            {
                NotifiyError(result.Messages);
                return RedirectToAction("Index");
            }
            NotifiySuccess(result.Messages);
            return RedirectToAction("Index");
        }
    }
}

MyBlog.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="assets/img/favicon.ico">
    <title>Mediumish - A Medium style template by WowThemes.net</title>
    <!-- Bootstrap core CSS -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">
    <!-- Fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/assets/css/mediumish.css" rel="stylesheet">

</head>
<body>

    <!-- Begin Nav
    ================================================== -->
    <nav class="navbar navbar-toggleable-md navbar-light bg-white fixed-top mediumnavigation">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="container">
            <!-- Begin Logo -->
            @*  <a class="navbar-brand" href="index.html">
            <img src="~/assets/img/logo.png" alt="logo">
            </a> *@
            <div class="mainheading">
                <h1 class="sitetitle">Mediumish</h1>

            </div>
            <!-- End Logo -->
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <!-- Begin Menu -->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="IndexTop5">Article Top 5</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="GetSubjects">Subjects</a>
                    </li>

                </ul>
                @if (User.IsInRole("Author"))
                {
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Profile
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                                <a class="dropdown-item" asp-area="Author" asp-controller="Article" asp-action="Index">My Articles</a>
                                <a class="dropdown-item" asp-area="Author" asp-controller="Subject" asp-action="Index">My Subjects</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                <a class="nav-link text-dark" asp-area="Author" asp-controller="Profile" asp-action="Profile">Settings</a>
                            </div>
                        </li>
                    </ul>
                }
                else
                {

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    </ul>
                }
            </div>

            <!-- End Menu -->
            <!-- Begin Search -->
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <span class="search-icon"><svg class="svgIcon-use" width="25" height="25" viewbox="0 0 25 25"><path d="M20.067 18.933l-4.157-4.157a6 6 0 1 0-.884.884l4.157 4.157a.624.624 0 1 0 .884-.884zM6.5 11c0-2.62 2.13-4.75 4.75-4.75S16 8.38 16 11s-2.13 4.75-4.75 4.75S6.5 13.62 6.5 11z"></path></svg></span>
            </form>
            <!-- End Search -->
        </div>

    </nav>
    <!-- End Nav
    ================================================== -->
    <!-- Begin Site Title
    ================================================== -->
    <div class="container">
        <div>
            <hr />
        </div>
        @RenderBody()
        <!-- End Site Title
        ================================================== -->
        <!-- Begin Footer
        ================================================== -->
        <div class="footer">
            <p class="pull-left">
                Copyright &copy; 1999 SONA Kalitenin Adresi
            </p>

            <div class="clearfix">
            </div>
        </div>
        <!-- End Footer
        ================================================== -->

    </div>
    <!-- /.container -->
    <!-- Bootstrap core JavaScript
        ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/ie10-viewport-bug-workaround.js"></script>
    @await Component.InvokeAsync("Notyf");
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>